name: preview-page

on: pull_request

jobs:
  deploy:
    name: deploy_preview_site
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile
      - run: yarn run test
      - run: yarn run generate:deploy --fail-on-page-error

      - name: Install aws-cli
        uses: chrislennon/action-aws-cli@v1.1
      - name: Deploy preview page
        run: |
          aws s3 mb s3://preview-covid19-aomori-${GITHUB_SHA}/
          aws s3 website s3://preview-covid19-aomori-${GITHUB_SHA}/ --index-document index.html --error-document 404.html
           aws s3api put-bucket-policy --bucket preview-covid19-aomori-${GITHUB_SHA} --policy "{\"Version\":\"2008-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":\"s3:GetObject\",\"Resource\":\"arn:aws:s3:::preview-covid19-aomori-${GITHUB_SHA}/*\"}]}"
          aws s3 sync dist/ s3://preview-covid19-aomori-${GITHUB_SHA}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
      - name: Comment
        uses: actions/github-script@0.9.0
        with:
          script: |
            const comment = 'preview page is http://preview-covid19-aomori-' + context.sha + '.s3-website-ap-northeast-1.amazonaws.com/'
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })
